"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { Building2, ClipboardCheck, Flag, Plane, Users } from "lucide-react";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { FactValue } from "@/components/shared/fact-value";
import { cn } from "@/lib/utils";

const stages = [
  {
    id: "factory",
    marker: "Factory",
    action: "Build",
    eyebrow: "Where performance starts",
    heading: "The impact begins before the car moves.",
    body: "Energy, materials and the people who build the car are part of the same operating story as performance. The route starts with evidence from the team’s home base.",
    factId: "e25-solar-gj",
    factLabel: "Electricity generated by solar panels on the factory roof",
    icon: Building2,
    image: "/brand/amr26-active-aero.png",
    imagePosition: "object-center",
  },
  {
    id: "freight",
    marker: "In transit",
    action: "Move",
    eyebrow: "Factory to freight",
    heading: "Every race starts with movement.",
    body: "Cars, parts and garage equipment move between countries. Published freight evidence makes one of racing’s less visible impacts easier to understand.",
    factId: "e25-saf-avoided",
    factLabel: "Air freight emissions avoided through Sustainable Aviation Fuel",
    icon: Plane,
    image: "/brand/amr26-launch-quarter.jpg",
    imagePosition: "object-[62%_center]",
  },
  {
    id: "circuit",
    marker: "At the circuit",
    action: "Race",
    eyebrow: "Freight to garage",
    heading: "What changes when the team arrives.",
    body: "The circuit chapter shows reported trackside evidence where it exists and says when regional detail is unavailable. You can see the result and inspect the source behind it.",
    factId: "e25-event-energy-cut",
    factLabel: "Cut in paddock event energy emissions at European races",
    icon: Flag,
    image: "/brand/amr26-launch-rear.jpg",
    imagePosition: "object-center",
  },
  {
    id: "community",
    marker: "Beyond the garage",
    action: "Connect",
    eyebrow: "Race to community",
    heading: "A race weekend reaches beyond the track.",
    body: "Inclusion and community stay on the main route. Partner programmes connect racing, technology and future careers to people outside the team.",
    factId: "c25-mam-day-students",
    factLabel: "Students engaged at Make A Mark Day with partners including Cognizant",
    icon: Users,
    image: "/brand/amr26-launch-front.jpg",
    imagePosition: "object-center",
  },
  {
    id: "evidence",
    marker: "After race day",
    action: "Verify",
    eyebrow: "Impact to evidence",
    heading: "The story ends at the source.",
    body: "Governance turns claims into evidence you can question. Each figure keeps its status, report page and source notes throughout the experience.",
    factId: "g25-assurance",
    factLabel: "External assurance of the team’s greenhouse gas inventory",
    icon: ClipboardCheck,
    image: "/brand/amr26-render-rear.jpg",
    imagePosition: "object-center",
  },
] as const;

export function JourneyPreview() {
  const [active, setActive] = useState<string>(stages[0].id);
  const reduceMotion = useReducedMotion();
  const sectionRefs = useRef(new Map<string, HTMLElement>());
  const activeIndex = Math.max(stages.findIndex((stage) => stage.id === active), 0);
  const activeStage = stages[activeIndex];

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((entry) => entry.isIntersecting)
          .sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
        if (visible?.target instanceof HTMLElement) setActive(visible.target.dataset.stage ?? stages[0].id);
      },
      { rootMargin: "-28% 0px -45% 0px", threshold: [0, 0.2, 0.5, 0.8] },
    );
    sectionRefs.current.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  return (
    <section id="route" className="relative border-b border-line bg-surface">
      <div className="mx-auto w-full max-w-[1600px] lg:grid lg:grid-cols-[minmax(24rem,0.9fr)_minmax(0,1.1fr)]">
        <aside className="top-14 z-10 self-start overflow-hidden border-b border-line bg-bg lg:sticky lg:h-[calc(100svh-3.5rem)] lg:border-r lg:border-b-0">
          <div className="relative flex h-full min-h-[33rem] flex-col p-4 sm:min-h-[40rem] sm:p-6 lg:p-10">
            <div className="relative z-20 flex items-start justify-between gap-5">
              <div>
                <p className="label text-lime">The car’s route</p>
                <AnimatePresence mode="wait" initial={false}>
                  <motion.p
                    key={activeStage.eyebrow}
                    initial={reduceMotion ? false : { opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={reduceMotion ? undefined : { opacity: 0, y: -8 }}
                    transition={{ duration: 0.18 }}
                    className="mt-2 text-sm text-ink-2"
                  >
                    {activeStage.eyebrow}
                  </motion.p>
                </AnimatePresence>
              </div>
              <p className="label text-ink">{activeStage.action}</p>
            </div>

            <div className="pointer-events-none absolute inset-x-0 top-[16%] bottom-[18%] overflow-hidden" aria-hidden>
              <AnimatePresence initial={false}>
                <motion.div
                  key={activeStage.id}
                  className="absolute inset-0"
                  initial={reduceMotion ? false : { opacity: 0, scale: 1.035 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={reduceMotion ? undefined : { opacity: 0 }}
                  transition={{ duration: 0.28, ease: "easeOut" }}
                >
                  <Image
                    src={activeStage.image}
                    alt=""
                    fill
                    sizes="(max-width: 1024px) 100vw, 50vw"
                    className={cn("object-cover", activeStage.imagePosition)}
                  />
                  <div className="absolute inset-x-0 top-0 h-14 bg-bg/55" />
                  <div className="absolute inset-x-0 bottom-0 h-14 bg-bg/55" />
                </motion.div>
              </AnimatePresence>
              <div className="absolute inset-x-0 top-1/2 h-px bg-lime/75" />
              <div className="absolute top-1/2 left-[18%] size-2 -translate-x-1/2 -translate-y-1/2 bg-lime" />
              <div className="absolute top-1/2 right-[12%] size-2 translate-x-1/2 -translate-y-1/2 border border-lime" />
            </div>

            <div className="relative z-20 mt-auto">
              <nav aria-label="Car route">
                <ol className="grid grid-cols-5 border-y border-line">
                  {stages.map((stage, index) => {
                    const selected = stage.id === active;
                    const Icon = stage.icon;
                    return (
                      <li key={stage.id}>
                        <a
                          href={`#${stage.id}`}
                          aria-current={selected ? "step" : undefined}
                          className={cn(
                            "group flex min-h-16 flex-col justify-between border-l border-line px-2 py-2 transition-colors first:border-l-0 sm:px-3",
                            selected ? "bg-lime text-lime-ink" : "bg-bg text-ink-3 hover:bg-surface-2 hover:text-ink",
                          )}
                        >
                          <span className="label text-current">{String.fromCharCode(65 + index)}</span>
                          <span className="hidden text-xs font-semibold sm:block">{stage.marker}</span>
                          <Icon className="size-4 sm:hidden" aria-hidden />
                        </a>
                      </li>
                    );
                  })}
                </ol>
              </nav>
              <div className="mt-4 flex items-center justify-between gap-4">
                <p className="label">Scroll to move the car</p>
                <p className="label text-ink">{activeStage.marker}</p>
              </div>
            </div>
          </div>
        </aside>

        <div>
          <div className="px-4 py-14 sm:px-8 sm:py-20 lg:px-12 lg:py-24">
            <p className="label">A continuous impact story</p>
            <h2 className="display mt-4 max-w-[10ch] text-[clamp(3.5rem,8vw,8rem)]">The full picture travels with the car.</h2>
            <p className="mt-6 max-w-xl text-lg leading-relaxed text-ink-2">
              Follow one clear route through environment, inclusion, community and governance. Nothing is hidden by your topic
              choices.
            </p>
          </div>

          {stages.map((stage) => {
            const Icon = stage.icon;
            return (
              <article
                key={stage.id}
                id={stage.id}
                data-stage={stage.id}
                ref={(node) => {
                  if (node) sectionRefs.current.set(stage.id, node);
                  else sectionRefs.current.delete(stage.id);
                }}
                className="flex min-h-[86svh] scroll-mt-28 flex-col justify-center border-t border-line px-4 py-16 sm:px-8 sm:py-24 lg:min-h-[calc(100svh-3.5rem)] lg:scroll-mt-14 lg:px-12"
              >
                <div className="flex items-center gap-3">
                  <span className="flex size-10 items-center justify-center border border-line bg-bg">
                    <Icon className="size-4 text-lime" aria-hidden />
                  </span>
                  <div>
                    <p className="label">{stage.action}</p>
                    <p className="text-sm font-semibold">{stage.marker}</p>
                  </div>
                </div>
                <h3 className="display mt-8 max-w-[11ch] text-[clamp(3rem,7vw,6.8rem)]">{stage.heading}</h3>
                <p className="mt-6 max-w-xl text-base leading-relaxed text-ink-2 sm:text-lg">{stage.body}</p>
                <div className="mt-10 border-y border-line bg-bg px-4 py-6 sm:px-6 sm:py-8">
                  <FactValue id={stage.factId} size="xl" label={stage.factLabel} />
                </div>
              </article>
            );
          })}
        </div>
      </div>
    </section>
  );
}
